import { useMemo, useRef, useState, type ReactNode } from "react";
import feather from "feather-icons";

type WikiLevel = "Start here" | "Methods" | "Advanced" | "Reference";

type WikiEntry = {
  id: string;
  level: WikiLevel;
  title: string;
  summary: string;
  search: string;
  content: ReactNode;
};

type WikiIconName = keyof typeof feather.icons;

function WikiIcon({ name, size = 16 }: { name: WikiIconName; size?: number }) {
  const markup = feather.icons[name].toSvg({
    width: size,
    height: size,
    "stroke-width": 1.8,
    "aria-hidden": "true",
  });
  return (
    <span
      className="icon"
      aria-hidden="true"
      dangerouslySetInnerHTML={{ __html: markup }}
    />
  );
}

function Code({ children }: { children: string }) {
  return (
    <pre className="wiki-code">
      <code>{children}</code>
    </pre>
  );
}

function Note({ children }: { children: ReactNode }) {
  return (
    <aside className="wiki-note">
      <WikiIcon name="info" />
      <div>{children}</div>
    </aside>
  );
}

function Method({
  family,
  learns,
  useWhen,
  tradeoff,
  expects,
  example,
  localBehaviour,
  knobs,
}: {
  family: string;
  learns: string;
  useWhen: string;
  tradeoff: string;
  expects: string;
  example: string;
  localBehaviour: string;
  knobs: string;
}) {
  return (
    <>
      <div className="wiki-method-grid">
        <div>
          <h3>Family</h3>
          <p>{family}</p>
        </div>
        <div>
          <h3>What it learns</h3>
          <p>{learns}</p>
        </div>
        <div>
          <h3>Use it when</h3>
          <p>{useWhen}</p>
        </div>
        <div>
          <h3>Main trade-off</h3>
          <p>{tradeoff}</p>
        </div>
      </div>
      <h3>Data it expects</h3>
      <p>{expects}</p>
      <Code>{example}</Code>
      <h3>What osAi does locally</h3>
      <p>{localBehaviour}</p>
      <h3>Controls that matter most</h3>
      <p>{knobs}</p>
    </>
  );
}

const pairwiseExample =
  '{"prompt":"Explain gravity simply.","chosen":"Gravity pulls objects toward each other.","rejected":"Gravity makes objects glow."}';
const rewardExample =
  '{"prompt":"Give one safety tip.","response":"Wear eye protection.","reward":1.0}';

const wikiEntries: WikiEntry[] = [
  {
    id: "orientation",
    level: "Start here",
    title: "Training 101: the big picture",
    summary:
      "Understand fine-tuning, alignment, adapters, rollouts, rewards, and quantized bases before choosing settings.",
    search:
      "beginner basics 101 fine tuning alignment adapter lora qlora qat base policy rollout reward preference internet local",
    content: (
      <>
        <p>
          A pretrained model already knows language and broad patterns.
          Fine-tuning teaches it how you want it to answer or what new examples
          it should imitate. Alignment then changes which answers it prefers,
          using comparisons, feedback, or rewards.
        </p>
        <div className="wiki-definition-grid">
          <div>
            <h3>Base model</h3>
            <p>
              The original quantized MLX or GGUF checkpoint. osAi keeps these
              weights frozen during training.
            </p>
          </div>
          <div>
            <h3>LoRA adapter</h3>
            <p>
              Small trainable matrices attached to selected model layers. The
              gradients update these matrices instead of copying the full model.
            </p>
          </div>
          <div>
            <h3>Policy</h3>
            <p>
              The model that currently generates answers: the quantized base
              plus the latest adapter.
            </p>
          </div>
          <div>
            <h3>Rollout</h3>
            <p>
              An answer generated by the current policy during alignment. It is
              experience for the next gradient update.
            </p>
          </div>
          <div>
            <h3>Preference</h3>
            <p>
              A chosen answer paired with a rejected answer for the same prompt.
            </p>
          </div>
          <div>
            <h3>Reward</h3>
            <p>
              A finite number indicating how desirable a response is. Positive
              raises its probability; negative lowers it.
            </p>
          </div>
        </div>
        <Note>
          <strong>“Online RL” does not mean online servers.</strong> In osAi it
          means the local model generates fresh answers while the run is active.
          Generation, scoring, gradients, and saved rollouts stay on this
          computer.
        </Note>
      </>
    ),
  },
  {
    id: "workflow",
    level: "Start here",
    title: "End-to-end workflow",
    summary:
      "Follow one training session from source data to a tested adapter and deployment bundle.",
    search:
      "workflow pipeline stage end to end model dataset fine tune align rollouts score backprop output test validation",
    content: (
      <>
        <ol className="wiki-steps">
          <li>
            <strong>Choose a model.</strong> Use an osCode tier or a complete
            local custom model. Auto chooses MLX on supported Apple silicon and
            llama.cpp elsewhere.
          </li>
          <li>
            <strong>Prepare data.</strong> Put one JSON object on each line of
            <code> train.jsonl</code>, with optional <code>valid.jsonl</code>{" "}
            and
            <code> test.jsonl</code>, or select one JSON/JSONL file in the app.
          </li>
          <li>
            <strong>Fine-tune.</strong> The quantized base stays frozen while
            reverse-mode backpropagation updates LoRA tensors.
          </li>
          <li>
            <strong>Align.</strong> With live rollouts enabled, the fine-tuned
            policy generates answers, osAi scores or pairs them using your local
            references, and the selected objective backpropagates through the
            adapter.
          </li>
          <li>
            <strong>Publish.</strong> The session contains the adapter,
            base-plus-adapter layout, manifests, logs, rollouts, and a
            standalone quantized deployment bundle.
          </li>
          <li>
            <strong>Evaluate.</strong> Compare held-out prompts before and after
            training. Check quality, regressions, safety, and repeated-run
            stability before distributing a model.
          </li>
        </ol>
        <Note>
          For a first run, start with automatic hardware fitting, one epoch,
          prompt masking enabled, and a small clean dataset. Prove the pipeline
          works before increasing context, rank, layers, or dataset size.
        </Note>
      </>
    ),
  },
  {
    id: "dataset-files",
    level: "Start here",
    title: "Dataset files and splits",
    summary:
      "Learn the JSONL structure, train/validation/test roles, and how the app stages selected files.",
    search:
      "dataset file folder json jsonl ndjson train valid validation test split utf8 individual selected schema",
    content: (
      <>
        <p>
          JSONL is a text file containing one complete JSON object per line. It
          streams efficiently, makes a bad row easy to locate, and works for
          large datasets without loading the whole file into memory.
        </p>
        <Code>{`my-dataset/
├── train.jsonl       required; gradient updates
├── valid.jsonl       optional; tuning and overfit checks
└── test.jsonl        optional; final held-out evaluation`}</Code>
        <p>
          The app also accepts a single <code>.json</code>, <code>.jsonl</code>,
          or <code>.ndjson</code> file. It creates a private canonical
          <code> train.jsonl</code> inside that session. Relative media paths
          are resolved beside the originally selected file before staging.
        </p>
        <h3>Split discipline</h3>
        <ul>
          <li>Do not place the same example in both training and test data.</li>
          <li>
            Keep test data untouched until settings have been chosen using the
            validation split.
          </li>
          <li>
            Remove secrets, private data, duplicates, corrupted media, and
            examples you do not have permission to train on.
          </li>
          <li>
            Prefer fewer accurate examples over a larger set with contradictory
            answers.
          </li>
        </ul>
      </>
    ),
  },
  {
    id: "supervised-data",
    level: "Start here",
    title: "Supervised fine-tuning data",
    summary:
      "See accepted text, completion, chat, Alpaca/Dolly, QA, translation, and tool-call layouts.",
    search:
      "sft supervised text prompt completion messages chat alpaca dolly instruction input output question answer query response source target sharegpt tool call",
    content: (
      <>
        <p>
          Supervised fine-tuning teaches the model to reproduce the desired
          target. A dataset may use several common source schemas; osAi
          validates and normalizes them into one canonical chat representation.
        </p>
        <h3>Prompt and completion</h3>
        <Code>
          {
            '{"prompt":"Name the primary colours.","completion":"Red, yellow, and blue."}'
          }
        </Code>
        <h3>OpenAI-style messages</h3>
        <Code>
          {
            '{"messages":[{"role":"user","content":"Say hello."},{"role":"assistant","content":"Hello!"}]}'
          }
        </Code>
        <h3>Alpaca or Dolly</h3>
        <Code>
          {
            '{"instruction":"Summarize the note.","input":"The meeting moved to Friday.","output":"The meeting is now Friday."}'
          }
        </Code>
        <h3>Other accepted pairs</h3>
        <p>
          <code>question/answer</code>, <code>query/response</code>,
          <code>source/target</code>, ShareGPT conversations, raw
          <code> text</code>, and preference rows are accepted. When a
          preference row is used for supervised training, the chosen answer
          becomes the target.
        </p>
        <Note>
          Prompt masking means loss is calculated on the assistant answer rather
          than teaching the model to reproduce the user prompt. It is the safer
          default for instruction tuning.
        </Note>
      </>
    ),
  },
  {
    id: "multimodal-data",
    level: "Start here",
    title: "Images, video, and audio",
    summary:
      "Build local VLM examples and understand which media paths and training stages are supported.",
    search:
      "multimodal vlm vision image images video videos audio audios media caption transcription processor mmproj gemma minicpm phi",
    content: (
      <>
        <p>
          Multimodal supervised rows combine a text target with local media. Use
          paths relative to the dataset or absolute paths. Embedded base64 and
          <code> data:</code> values are accepted; remote media URLs are not
          fetched.
        </p>
        <h3>Image instruction</h3>
        <Code>
          {
            '{"messages":[{"role":"user","content":"What is shown?"},{"role":"assistant","content":"A blue notebook."}],"images":["media/notebook.jpg"]}'
          }
        </Code>
        <h3>Video description</h3>
        <Code>
          {
            '{"prompt":"Describe the motion.","completion":"The pen moves left.","videos":["media/pen.mp4"]}'
          }
        </Code>
        <h3>Audio transcription</h3>
        <Code>
          {
            '{"prompt":"Transcribe this clip.","completion":"Hello world.","audio":["media/hello.wav"]}'
          }
        </Code>
        <p>
          A custom VLM must include its matching processor and media-tower
          weights. Video needs a compatible video processor. Audio needs a
          supported multimodal checkpoint. The app exposes image size, sampled
          video frames, frame rate, and assistant-boundary controls under
          Advanced.
        </p>
        <Note>
          Current alignment objectives operate on text. Use multimodal examples
          for supervised VLM fine-tuning, then use text prompts, references, and
          rewards for the alignment stage.
        </Note>
      </>
    ),
  },
  {
    id: "alignment-data",
    level: "Start here",
    title: "Alignment data: pairs, labels, and rewards",
    summary:
      "Choose the correct row shape before selecting an offline preference or policy-gradient objective.",
    search:
      "alignment dataset preference pair chosen rejected preferred winner loser binary label thumbs reward score response old logprob schema",
    content: (
      <>
        <h3>Pairwise preference</h3>
        <Code>{pairwiseExample}</Code>
        <p>
          Accepted aliases include <code>preferred/non_preferred</code>,
          <code>winner/loser</code>, and ranked
          <code> response_j/response_k/label</code>. Conversational chosen and
          rejected message lists are also normalized.
        </p>
        <h3>Binary feedback</h3>
        <Code>
          {
            '{"prompt":"Give one safety tip.","completion":"Wear eye protection.","label":"thumbs_up"}'
          }
        </Code>
        <p>
          Labels such as true/false, 1/0, desirable/undesirable, liked/disliked,
          and positive/negative become +1 or −1 rewards.
        </p>
        <h3>Scored response</h3>
        <Code>{rewardExample}</Code>
        <p>
          <code>score</code> and <code>value</code> are accepted aliases for a
          finite numeric reward. Advanced static PPO data may also include
          <code> old_logprob</code>.
        </p>
        <Note>
          Keep one schema throughout a split. RLOO and GRPO static data require
          multiple response rows sharing each prompt; GRPO additionally needs
          reward variation within every prompt group.
        </Note>
      </>
    ),
  },
  {
    id: "choose-method",
    level: "Methods",
    title: "Choose an alignment method",
    summary:
      "Use this decision guide to pick a dependable objective for the signal you actually have.",
    search:
      "choose compare decision method auto dpo ipo simpo orpo cpo kto ppo reinforce rloo grpo pairwise binary policy gradient rl",
    content: (
      <>
        <div className="wiki-table-wrap">
          <table className="wiki-table">
            <thead>
              <tr>
                <th>Your signal</th>
                <th>Start with</th>
                <th>Consider next</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Chosen and rejected answer pairs</td>
                <td>DPO</td>
                <td>IPO for noisy pairs; SimPO/CPO for reference-free work</td>
              </tr>
              <tr>
                <td>SFT and preference learning together</td>
                <td>ORPO</td>
                <td>CPO if a compact reference-free objective is preferred</td>
              </tr>
              <tr>
                <td>Independent likes and dislikes</td>
                <td>KTO</td>
                <td>Balance positive and negative labels first</td>
              </tr>
              <tr>
                <td>Fresh local answers with scalar feedback</td>
                <td>PPO</td>
                <td>REINFORCE for simplicity; RLOO/GRPO for grouped samples</td>
              </tr>
              <tr>
                <td>You want osAi to infer the schema</td>
                <td>Auto</td>
                <td>DPO for pairs, PPO for reward rows</td>
              </tr>
            </tbody>
          </table>
        </div>
        <Note>
          The most sophisticated objective cannot repair bad feedback. First
          verify that chosen answers are truly better, rewards are consistently
          scaled, and prompts resemble real use.
        </Note>
      </>
    ),
  },
  {
    id: "auto",
    level: "Methods",
    title: "Auto alignment",
    summary:
      "Let osAi select a conservative method from the validated dataset schema.",
    search:
      "auto automatic alignment dpo ppo schema default pairwise reward orpo prompt",
    content: (
      <Method
        family="Schema-based selection"
        learns="The objective chosen after osAi validates the complete alignment split."
        useWhen="You are beginning, your dataset has one clear schema, or you want a dependable baseline."
        tradeoff="Auto cannot judge whether the feedback itself is high quality or whether a more specialized objective fits your research goal."
        expects="Preference pairs or scored response rows. Do not mix schemas in one split."
        example={pairwiseExample}
        localBehaviour="Auto resolves pairwise data to DPO and reward data to PPO. In a non-interactive fine-tune-and-align run, preference data selects DPO unless ORPO was selected explicitly in the app."
        knobs="Start with automatic hardware fitting and default alignment controls. Change the method only after measuring a baseline."
      />
    ),
  },
  {
    id: "dpo",
    level: "Methods",
    title: "DPO — Direct Preference Optimization",
    summary:
      "A dependable reference-relative objective for chosen and rejected answer pairs.",
    search:
      "dpo direct preference optimization pairwise reference policy beta chosen rejected margin robust default",
    content: (
      <Method
        family="Offline pairwise preference optimization"
        learns="A larger chosen-versus-rejected log-probability margin than the frozen reference policy."
        useWhen="You have trustworthy pairs and want the standard, well-understood preference baseline."
        tradeoff="It uses a reference comparison and can push noisy pairs too strongly when beta or the learning rate is poorly chosen."
        expects="One prompt with one chosen and one rejected text response."
        example={pairwiseExample}
        localBehaviour="With live rollouts, the current policy first generates a fresh answer. osAi compares its local similarity with the supplied chosen and rejected references, creates a new pair, and backpropagates DPO. Static mode uses the pair unchanged."
        knobs="Beta controls preference strength/temperature. Also watch alignment learning rate, update count, and pair quality."
      />
    ),
  },
  {
    id: "ipo",
    level: "Methods",
    title: "IPO — Identity Preference Optimization",
    summary:
      "A finite squared-margin alternative when DPO may over-separate noisy preferences.",
    search:
      "ipo identity preference optimization finite squared controlled target noisy pairwise beta margin",
    content: (
      <Method
        family="Offline pairwise preference optimization"
        learns="A controlled finite preference margin instead of continually rewarding greater separation."
        useWhen="Annotators are imperfect, preferences are close calls, or DPO appears to overfit and become overconfident."
        tradeoff="Its target is sensitive to beta; a poor target can underfit obvious preferences or still amplify noise."
        expects="The same prompt/chosen/rejected rows used by DPO."
        example={
          '{"prompt":"Answer politely.","chosen":"I cannot help with that, but I can suggest a safe alternative.","rejected":"No."}'
        }
        localBehaviour="Live rollout pairing is local and identical in shape to DPO; the difference is the differentiable loss applied to the resulting margin."
        knobs="Tune beta conservatively and compare held-out preference accuracy with DPO at the same learning rate and update budget."
      />
    ),
  },
  {
    id: "simpo",
    level: "Methods",
    title: "SimPO — Simple Preference Optimization",
    summary:
      "Reference-free, length-normalized preference learning with an explicit target margin.",
    search:
      "simpo simple preference optimization reference free length normalized gamma margin memory pairwise",
    content: (
      <Method
        family="Offline reference-free pairwise optimization"
        learns="A length-normalized chosen-over-rejected margin without subtracting a frozen reference margin."
        useWhen="Reference computation is undesirable, memory is tight, or answer length is distorting ordinary pairwise scores."
        tradeoff="Gamma and beta need tuning; removing the reference comparison can reduce the anchor to the original policy."
        expects="One chosen and one rejected response for each prompt."
        example={
          '{"prompt":"Define photosynthesis in one sentence.","chosen":"Plants use light to convert water and carbon dioxide into stored chemical energy.","rejected":"Photosynthesis is when plants sleep."}'
        }
        localBehaviour="osAi constructs or reads the preference pair, normalizes sequence log-probability by response length, and backpropagates the SimPO margin."
        knobs="Gamma is the target margin. Tune gamma, beta, maximum sequence length, and response-length balance together."
      />
    ),
  },
  {
    id: "orpo",
    level: "Methods",
    title: "ORPO — Odds Ratio Preference Optimization",
    summary:
      "Combines chosen-answer likelihood with an odds-ratio preference objective.",
    search:
      "orpo odds ratio preference optimization sft chosen likelihood combined pairwise overfit",
    content: (
      <Method
        family="Combined supervised and pairwise preference optimization"
        learns="To model the chosen answer well while increasing its odds relative to the rejected answer."
        useWhen="Chosen-answer quality should remain an explicit supervised target during preference alignment."
        tradeoff="The combined signal is stronger and can overfit a tiny or repetitive preference dataset."
        expects="Prompt/chosen/rejected text pairs. The chosen response carries both supervised and preference signal."
        example={
          '{"prompt":"Write a concise commit message.","chosen":"Fix MLX progress parsing","rejected":"changes"}'
        }
        localBehaviour="osAi backpropagates chosen negative log-likelihood plus a beta-weighted odds-ratio loss. Select ORPO explicitly in the app for deterministic non-interactive behavior."
        knobs="Use a modest alignment learning rate and update count. Monitor chosen-answer loss as well as preference behavior."
      />
    ),
  },
  {
    id: "cpo",
    level: "Methods",
    title: "CPO — Contrastive Preference Optimization",
    summary:
      "A compact reference-free contrastive margin plus chosen-answer likelihood.",
    search:
      "cpo contrastive preference optimization reference free chosen likelihood compact pairwise beta",
    content: (
      <Method
        family="Offline reference-free pairwise optimization"
        learns="A chosen-over-rejected contrastive margin while preserving likelihood of the chosen answer."
        useWhen="You want a compact preference objective without a frozen reference term."
        tradeoff="It depends heavily on chosen-response quality and can learn annotation artifacts when pairs are weak."
        expects="Clean prompt/chosen/rejected text pairs."
        example={
          '{"prompt":"State the uncertainty.","chosen":"The evidence suggests this, but it is not conclusive.","rejected":"This is certainly true."}'
        }
        localBehaviour="The quantized base remains frozen. osAi differentiates the contrastive margin and chosen-likelihood term into the adapter only."
        knobs="Beta, alignment learning rate, and balanced response lengths are the main controls."
      />
    ),
  },
  {
    id: "kto",
    level: "Methods",
    title: "KTO — Kahneman-Tversky Optimization",
    summary:
      "Learn from independent desirable and undesirable responses instead of requiring explicit pairs.",
    search:
      "kto kahneman tversky binary feedback thumbs up down label desirable undesirable reward positive negative reference",
    content: (
      <Method
        family="Binary-feedback alignment"
        learns="To raise desirable responses and lower undesirable responses relative to the frozen policy."
        useWhen="Feedback arrives as likes/dislikes or pass/fail labels and natural chosen/rejected pairs do not exist."
        tradeoff="Label imbalance can dominate the update, and zero-valued labels are invalid after normalization."
        expects="A prompt, response or completion, and a binary label; explicit positive or negative rewards also work."
        example={
          '{"prompt":"Suggest a strong password.","completion":"Use a unique passphrase and a password manager.","label":"thumbs_up"}'
        }
        localBehaviour="Labels normalize to +1 or −1. With live rollouts, osAi generates a local response and derives its reward from your local pair or scored-response reference before applying KTO."
        knobs="Balance positive and negative examples, inspect beta, and avoid mixing different label meanings across sources."
      />
    ),
  },
  {
    id: "ppo",
    level: "Methods",
    title: "PPO — Proximal Policy Optimization",
    summary:
      "Use clipped policy-ratio updates to limit how far a rewarded answer moves the policy in one step.",
    search:
      "ppo proximal policy optimization online rl policy gradient clipped ratio clip reward old logprob critic actor",
    content: (
      <Method
        family="Policy-gradient alignment with clipped updates"
        learns="To increase rewarded generated answers while clipping large policy-ratio changes."
        useWhen="You want fresh local rollouts with conservative per-update movement."
        tradeoff="Results are sensitive to reward quality and clip width. osAi uses the clipped policy surrogate without a learned critic model."
        expects="With live rollouts, preference pairs or scored references provide prompts and local scoring anchors. Static mode expects prompt/response/reward and optionally old_logprob."
        example={rewardExample}
        localBehaviour="The current local policy generates an answer, osAi derives a local similarity-based reward from your reference, and the clipped differentiable objective updates LoRA tensors. No reward or critic server is started."
        knobs="PPO clip, rollout temperature/top-p, reward scale, alignment learning rate, and update count."
      />
    ),
  },
  {
    id: "reinforce",
    level: "Methods",
    title: "REINFORCE",
    summary:
      "The simplest reward-weighted log-probability objective for fresh generated answers.",
    search:
      "reinforce monte carlo policy gradient reward weighted log probability online rl variance baseline",
    content: (
      <Method
        family="Critic-free policy gradient"
        learns="To increase the log-probability of positive-reward answers and decrease negative-reward answers."
        useWhen="You want a transparent, low-overhead policy-gradient baseline."
        tradeoff="Gradient variance is high because there is no learned critic or group baseline."
        expects="Live mode accepts preference or scored-response references. Static mode needs prompt/response/reward rows."
        example={
          '{"prompt":"Answer in valid JSON.","response":"{\\"status\\":\\"ok\\"}","reward":1.0}'
        }
        localBehaviour="osAi generates and scores answers locally, then multiplies response log-probability by the resulting advantage/reward and backpropagates it."
        knobs="Reward scaling, rollout diversity, learning rate, and a larger number of clean prompts matter more than extra model state."
      />
    ),
  },
  {
    id: "rloo",
    level: "Methods",
    title: "RLOO — REINFORCE Leave-One-Out",
    summary:
      "Reduce policy-gradient variance by comparing each answer with other answers for the same prompt.",
    search:
      "rloo reinforce leave one out baseline grouped rollouts multiple answers prompt reward variance critic free",
    content: (
      <Method
        family="Grouped critic-free policy gradient"
        learns="From each answer's reward minus the mean reward of the other answers generated for that prompt."
        useWhen="You can generate several answers per prompt and want a lower-variance REINFORCE-style update."
        tradeoff="It costs more generation and needs at least two answers for every prompt group."
        expects="Live mode needs references and at least two rollouts per prompt. Static rows repeat the same prompt with multiple scored responses."
        example={`{"prompt":"Give a two-word greeting.","response":"Hello there","reward":1.0}
{"prompt":"Give a two-word greeting.","response":"Words words","reward":-0.5}`}
        localBehaviour="osAi groups local rollouts by prompt, computes a leave-one-out baseline without a learned critic, and backpropagates the centered advantages."
        knobs="Rollouts per prompt, temperature, top-p, reward consistency, and alignment learning rate."
      />
    ),
  },
  {
    id: "grpo",
    level: "Methods",
    title: "GRPO — Group Relative Policy Optimization",
    summary:
      "Standardize rewards within each prompt group and combine clipped updates with a reference penalty.",
    search:
      "grpo group relative policy optimization grouped standardized reward variance clipped kl reference critic free rollouts",
    content: (
      <Method
        family="Grouped critic-free policy-gradient optimization"
        learns="From standardized within-group advantages while clipping policy movement and retaining a reference penalty."
        useWhen="You can afford several diverse local answers per prompt and want relative group feedback without training a critic."
        tradeoff="Every prompt needs at least two samples and non-zero reward variance; identical answers or scores make the group unusable."
        expects="Live mode needs reference rows and at least two rollouts per prompt. Static data repeats each prompt with several differently rewarded responses."
        example={`{"prompt":"Give a concise title.","response":"Local Model Training","reward":1.0}
{"prompt":"Give a concise title.","response":"A Very Long and Vague Document Name","reward":-0.2}
{"prompt":"Give a concise title.","response":"Training Guide","reward":0.7}`}
        localBehaviour="osAi generates each group locally, derives local scores from your references, standardizes the rewards, and applies a clipped GRPO loss with a reference penalty."
        knobs="Use at least 2 rollouts per prompt; 4 or more usually provides a more meaningful group. Tune temperature, beta/reference strength, clip width, and learning rate."
      />
    ),
  },
  {
    id: "local-rollouts",
    level: "Advanced",
    title: "Live local rollouts and static data",
    summary:
      "Understand exactly what osAi generates, scores, records, and reuses during alignment.",
    search:
      "live local online offline rollout static no live scorer similarity token f1 sequence manifest network internet fresh policy",
    content: (
      <>
        <h3>Live rollouts — default</h3>
        <p>
          The current base-plus-adapter policy generates fresh answers for your
          source prompts. Pairwise objectives compare each generated answer with
          local chosen/rejected references. Reward objectives derive a local
          token-and-sequence-similarity score from your pair or scored response.
        </p>
        <h3>Static alignment</h3>
        <p>
          Turning off live rollouts skips generation. Pairwise methods consume
          the supplied pairs unchanged. Policy-gradient methods consume existing
          <code> prompt/response/reward</code> rows. RLOO and GRPO still need
          valid prompt groups.
        </p>
        <h3>Audit trail</h3>
        <p>
          Generated rows are saved under <code>rollouts/train.jsonl</code>. The
          rollout manifest records dataset and adapter hashes, sampling
          settings, the scorer, and that network use was false.
        </p>
        <Note>
          The built-in similarity scorer is deterministic and private, but it is
          not a universal judge of correctness. For hard domains, curate strong
          references and independently evaluate factuality and safety.
        </Note>
      </>
    ),
  },
  {
    id: "qat-engines",
    level: "Advanced",
    title: "Quantized training, MLX, and GGUF",
    summary:
      "See what remains quantized, where gradients flow, and how language and multimodal engines differ.",
    search:
      "qat quantized training qlora lora mlx gguf llama cpp dequantize backprop gradient frozen base residual fusion vlm",
    content: (
      <>
        <p>
          osAi keeps the quantized base frozen and trains LoRA adapter tensors
          with reverse-mode gradients. It does not create a full floating-point
          copy of the base for training or publication.
        </p>
        <div className="wiki-definition-grid">
          <div>
            <h3>MLX</h3>
            <p>
              Gradient LoRA for quantized language models and compatible local
              VLMs. Auto uses AdamW. Apple silicon uses Metal; supported Linux
              systems can use CUDA/NCCL or CPU.
            </p>
          </div>
          <div>
            <h3>GGUF / llama.cpp</h3>
            <p>
              Native quantized sequence backward updates a GGUF LoRA adapter.
              Auto uses SGD. Metal, CUDA, Vulkan, and CPU depend on the host.
            </p>
          </div>
        </div>
        <p>
          GGUF VLM fine-tuning requires a matching quantized MLX VLM companion
          for the media-conditioned backward pass because llama.cpp does not
          expose media-projector backward APIs. osAi exports the learned
          language adapter to GGUF while preserving the GGUF and projector
          bytes.
        </p>
      </>
    ),
  },
  {
    id: "controls",
    level: "Advanced",
    title: "Training controls without guesswork",
    summary:
      "Understand context, batches, accumulation, epochs, rank, layers, learning rate, and checkpointing.",
    search:
      "hyperparameter settings context max sequence batch size gradient accumulation epoch iteration learning rate rank scale layers dropout checkpoint mask prompt memory",
    content: (
      <div className="wiki-control-list">
        <div>
          <h3>Context / maximum sequence length</h3>
          <p>
            Tokens retained from each example. Too small truncates information;
            larger values increase activation memory sharply.
          </p>
        </div>
        <div>
          <h3>Batch size and gradient accumulation</h3>
          <p>
            Batch size is examples processed together. Accumulation combines
            several microbatches before an optimizer update, simulating a larger
            batch with less peak memory.
          </p>
        </div>
        <div>
          <h3>Epochs and updates</h3>
          <p>
            One fine-tuning epoch is one full pass over the training split.
            Alignment updates are a separate fixed count. More is not always
            better; repeated small data overfits quickly.
          </p>
        </div>
        <div>
          <h3>Learning rate</h3>
          <p>
            Adapter step size. If loss becomes NaN or behavior changes wildly,
            lower it. If clean data produces no measurable change, cautiously
            raise it or train more layers.
          </p>
        </div>
        <div>
          <h3>Rank, scale, layers, and targets</h3>
          <p>
            These control adapter capacity and placement. Higher capacity may
            learn more but consumes memory and can overfit. Start small, then
            expand only when evaluation shows underfitting.
          </p>
        </div>
        <div>
          <h3>Gradient checkpointing</h3>
          <p>
            Recomputes activations during backward to save memory at the cost of
            extra compute. Keep it enabled on memory-constrained hardware.
          </p>
        </div>
      </div>
    ),
  },
  {
    id: "alignment-controls",
    level: "Advanced",
    title: "Alignment and rollout controls",
    summary:
      "Tune beta, gamma, clipping, rollout sampling, reward scale, and update count safely.",
    search:
      "alignment beta gamma ppo clip rollout samples per prompt max tokens temperature top p seed learning rate reward scale tuning",
    content: (
      <div className="wiki-control-list">
        <div>
          <h3>Beta</h3>
          <p>
            Preference temperature/weight and, for relevant methods, reference
            strength. Change it only with held-out comparisons.
          </p>
        </div>
        <div>
          <h3>Gamma</h3>
          <p>
            SimPO's desired preference margin. It is not a universal reward.
          </p>
        </div>
        <div>
          <h3>PPO clip</h3>
          <p>
            Limits policy-ratio movement for PPO and clipped group objectives.
            Too tight can stall; too wide weakens protection.
          </p>
        </div>
        <div>
          <h3>Rollouts per prompt</h3>
          <p>
            More samples improve group comparison but increase generation time.
            RLOO and GRPO require at least two.
          </p>
        </div>
        <div>
          <h3>Temperature and top-p</h3>
          <p>
            Control rollout diversity. Temperature 0 is deterministic. Group
            methods need enough diversity to produce different rewards.
          </p>
        </div>
        <div>
          <h3>Rollout token limit and seed</h3>
          <p>
            The token limit bounds time and answer length. The seed makes local
            sampling repeatable for comparison runs.
          </p>
        </div>
      </div>
    ),
  },
  {
    id: "evaluation",
    level: "Advanced",
    title: "Evaluation and proving learning",
    summary:
      "Separate successful optimization from genuine learning and deployment quality.",
    search:
      "evaluation eval validation test held out prove learning loss nan regression benchmark before after generalization overfit",
    content: (
      <>
        <p>
          A completed progress bar proves that the pipeline finished—not that
          the model improved. Evaluate the base and trained adapter on the same
          held- out prompts with deterministic decoding, then inspect more than
          one metric.
        </p>
        <ul>
          <li>Confirm training loss is finite and broadly trends downward.</li>
          <li>Measure preference win rate or reward on unseen prompts.</li>
          <li>
            Check formatting, factuality, refusal behavior, and multimodal
            grounding.
          </li>
          <li>
            Test capabilities that were not targeted to catch regressions.
          </li>
          <li>Repeat important runs with another seed.</li>
          <li>
            Retain dataset, model, adapter, and settings hashes so results are
            reproducible.
          </li>
        </ul>
        <Note>
          NaN loss, zero trainable answer tokens, identical GRPO rewards, or a
          dramatic training/test gap are faults to investigate—not successful
          learning signals.
        </Note>
      </>
    ),
  },
  {
    id: "outputs",
    level: "Reference",
    title: "Session outputs and deployment",
    summary:
      "Know where adapters, rollouts, manifests, logs, and final quantized bundles are stored.",
    search:
      "output session folder adapter base plus adapter merged model deployment manifest logs rollouts fusion hash quantized",
    content: (
      <>
        <Code>{`session/
├── manifests/
├── logs/
├── rollouts/                    alignment audit data
└── outputs/
    ├── base-plus-adapter/
    └── merged-model/            standalone residual bundle`}</Code>
        <p>
          The “merged” deployment does not rewrite the quantized base into full
          precision. MLX keeps original quantized tensors and embeds the exact
          adapter residual. GGUF keeps the original model and projector files
          and records the exact GGUF adapter. Manifests and SHA-256 checks bind
          the parts together.
        </p>
        <p>
          Keep the manifest with the output. It records how to load the model
          and protects against combining an adapter with the wrong base
          checkpoint.
        </p>
      </>
    ),
  },
  {
    id: "glossary",
    level: "Reference",
    title: "Glossary",
    summary:
      "Quick definitions for the vocabulary used throughout training and alignment.",
    search:
      "glossary token log probability logits loss gradient optimizer epoch batch checkpoint inference reference policy kl advantage reward model critic",
    content: (
      <dl className="wiki-glossary">
        <div>
          <dt>Token</dt>
          <dd>A model's small unit of text; not necessarily a whole word.</dd>
        </div>
        <div>
          <dt>Logit</dt>
          <dd>An unnormalized score for a possible next token.</dd>
        </div>
        <div>
          <dt>Log-probability</dt>
          <dd>
            The logarithm of probability, summed or averaged across response
            tokens.
          </dd>
        </div>
        <div>
          <dt>Loss</dt>
          <dd>A differentiable number the optimizer tries to reduce.</dd>
        </div>
        <div>
          <dt>Gradient</dt>
          <dd>
            How each trainable adapter value should change to reduce loss.
          </dd>
        </div>
        <div>
          <dt>Optimizer</dt>
          <dd>
            The rule that converts gradients into parameter updates, such as
            AdamW or SGD.
          </dd>
        </div>
        <div>
          <dt>Reference policy</dt>
          <dd>
            A frozen policy used to measure how far the trained policy moves.
          </dd>
        </div>
        <div>
          <dt>Advantage</dt>
          <dd>
            A reward adjusted by a baseline; positive is better than expected.
          </dd>
        </div>
        <div>
          <dt>Critic</dt>
          <dd>
            A learned value estimator. osAi's PPO, REINFORCE, RLOO, and GRPO
            paths do not train one.
          </dd>
        </div>
        <div>
          <dt>Inference</dt>
          <dd>Generating an answer without applying gradient updates.</dd>
        </div>
      </dl>
    ),
  },
];

const levels: WikiLevel[] = ["Start here", "Methods", "Advanced", "Reference"];

export function TrainingWiki() {
  const [query, setQuery] = useState("");
  const [contentsOpen, setContentsOpen] = useState(true);
  const [readingMode, setReadingMode] = useState<"page" | "continuous">("page");
  const [activeEntryId, setActiveEntryId] = useState(wikiEntries[0].id);
  const articlesRef = useRef<HTMLDivElement>(null);
  const entryLinksRef = useRef<Record<string, HTMLAnchorElement | null>>({});
  const terms = query.trim().toLocaleLowerCase().split(/\s+/).filter(Boolean);
  const filtered = useMemo(
    () =>
      wikiEntries.filter((entry) => {
        const haystack =
          `${entry.title} ${entry.summary} ${entry.search}`.toLocaleLowerCase();
        return terms.every((term) => haystack.includes(term));
      }),
    [query],
  );
  const activeIndex = Math.max(
    0,
    filtered.findIndex((entry) => entry.id === activeEntryId),
  );
  const activeEntry = filtered[activeIndex];

  function selectEntry(entryId: string) {
    setActiveEntryId(entryId);
    requestAnimationFrame(() => {
      entryLinksRef.current[entryId]?.scrollIntoView({
        behavior: "smooth",
        block: "nearest",
      });
      articlesRef.current?.scrollIntoView({
        behavior: "smooth",
        block: "start",
      });
    });
  }

  function movePage(offset: number) {
    const next = filtered[activeIndex + offset];
    if (next) selectEntry(next.id);
  }

  return (
    <div className="wiki-view">
      <div className="wiki-search-dock">
        <span className="wiki-title-tag">
          <WikiIcon name="book-open" />
          Ai Training Wiki
        </span>
        <label className="wiki-search">
          <WikiIcon name="search" />
          <input
            type="search"
            value={query}
            placeholder="Search methods, data, or settings"
            aria-label="Search the training wiki"
            autoComplete="off"
            spellCheck={false}
            onChange={(event) => setQuery(event.target.value)}
            onKeyDown={(event) => {
              if (event.key === "Escape") setQuery("");
            }}
          />
          {query && (
            <button
              type="button"
              aria-label="Clear wiki search"
              title="Clear search"
              onClick={() => setQuery("")}
            >
              <WikiIcon name="x" size={15} />
            </button>
          )}
        </label>
        <span aria-hidden="true" />
      </div>

      <div
        className={`wiki-layout ${contentsOpen ? "" : "contents-collapsed"}`}
      >
        <aside className="wiki-tool-rail" aria-label="Wiki view controls">
          <button
            type="button"
            className={contentsOpen ? "active" : undefined}
            aria-label={contentsOpen ? "Hide contents" : "Show contents"}
            title={contentsOpen ? "Hide contents" : "Show contents"}
            onClick={() => setContentsOpen((open) => !open)}
          >
            <WikiIcon name="sidebar" />
          </button>
          <span aria-hidden="true" />
          <button
            type="button"
            className={readingMode === "continuous" ? "active" : undefined}
            aria-label={
              readingMode === "page"
                ? "Use continuous scrolling"
                : "Use page mode"
            }
            title={
              readingMode === "page" ? "Continuous scrolling" : "Page mode"
            }
            onClick={() =>
              setReadingMode((mode) =>
                mode === "page" ? "continuous" : "page",
              )
            }
          >
            <WikiIcon
              name={readingMode === "page" ? "align-justify" : "book-open"}
            />
          </button>
          {readingMode === "page" && filtered.length > 0 && (
            <>
              <span aria-hidden="true" />
              <button
                type="button"
                aria-label="Previous wiki article"
                title="Previous article"
                disabled={activeIndex === 0}
                onClick={() => movePage(-1)}
              >
                <WikiIcon name="chevron-up" />
              </button>
              <button
                type="button"
                aria-label="Next wiki article"
                title="Next article"
                disabled={activeIndex === filtered.length - 1}
                onClick={() => movePage(1)}
              >
                <WikiIcon name="chevron-down" />
              </button>
            </>
          )}
        </aside>

        {contentsOpen && (
          <nav className="wiki-toc" aria-label="Wiki table of contents">
            <div className="wiki-toc-heading">
              <h2>Contents</h2>
              <p>
                {query
                  ? `${filtered.length} of ${wikiEntries.length} articles`
                  : `${wikiEntries.length} articles`}
              </p>
            </div>
            <div className="wiki-toc-scroll">
              {levels.map((level) => {
                const entries = filtered.filter(
                  (entry) => entry.level === level,
                );
                if (!entries.length) return null;
                return (
                  <section key={level}>
                    <h3>{level}</h3>
                    {entries.map((entry) => (
                      <a
                        key={entry.id}
                        href={`#wiki-${entry.id}`}
                        ref={(link) => {
                          entryLinksRef.current[entry.id] = link;
                        }}
                        className={
                          readingMode === "page" && entry.id === activeEntry?.id
                            ? "active"
                            : undefined
                        }
                        aria-current={
                          readingMode === "page" && entry.id === activeEntry?.id
                            ? "page"
                            : undefined
                        }
                        onClick={(event) => {
                          if (readingMode === "page") {
                            event.preventDefault();
                            selectEntry(entry.id);
                          } else {
                            setActiveEntryId(entry.id);
                          }
                        }}
                      >
                        {entry.title}
                      </a>
                    ))}
                  </section>
                );
              })}
            </div>
          </nav>
        )}

        <div
          className="wiki-articles"
          role="region"
          aria-label="Wiki articles"
          tabIndex={-1}
          ref={articlesRef}
        >
          {filtered.length ? (
            (readingMode === "page" && activeEntry
              ? [activeEntry]
              : filtered
            ).map((entry) => (
              <article id={`wiki-${entry.id}`} key={entry.id}>
                <header>
                  <span>{entry.level}</span>
                  <h2>{entry.title}</h2>
                  <p>{entry.summary}</p>
                </header>
                <div className="wiki-article-body">{entry.content}</div>
                {readingMode === "page" && (
                  <nav className="wiki-page-navigation" aria-label="Wiki pages">
                    <button
                      type="button"
                      disabled={activeIndex === 0}
                      onClick={() => movePage(-1)}
                    >
                      <WikiIcon name="arrow-left" />
                      Previous
                    </button>
                    <span>
                      Article {activeIndex + 1} of {filtered.length}
                    </span>
                    <button
                      type="button"
                      disabled={activeIndex === filtered.length - 1}
                      onClick={() => movePage(1)}
                    >
                      Next
                      <WikiIcon name="arrow-right" />
                    </button>
                  </nav>
                )}
              </article>
            ))
          ) : (
            <section className="wiki-empty-search">
              <WikiIcon name="search" size={24} />
              <h2>No matching article</h2>
              <p>
                Try a method name such as DPO or GRPO, a data field such as
                reward, or a training control such as batch size.
              </p>
              <button type="button" onClick={() => setQuery("")}>
                Clear search
              </button>
            </section>
          )}
        </div>
      </div>
    </div>
  );
}
